version: "3"

services:
  # Defines a service name
  workspace:
    build:
      # Sets the build context to the current directory
      context: .
      # Specifies the Dockerfile to use for the build
      dockerfile: .docker/Dockerfile.app
      # Specifies build-time variables (ARGs)
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $CONTAINER_USERNAME
        ARG_USER_UID: $CONTAINER_USER_UID
        ARG_USER_GID: $CONTAINER_USER_GID
        ARG_APP_SOURCE_REPO: $APP_SOURCE_REPO
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_DIRNAME: $APP_DIRNAME
        ARG_APP_SOURCE_BRANCH: $APP_SOURCE_BRANCH
    # Sets the image name for the built image
    image: $IMAGE_NAME:$IMAGE_TAG
    # Sets the hostname of the container
    hostname: $CONTAINER_HOSTNAME
    command:
      # Specifies the command to be executed when the container is run
      - bash
      - $CONTAINER_LAUNCH_SCRIPT
    # set the environment variables
    environment:
      USER_UID: $CONTAINER_USER_UID
      USER_GID: $CONTAINER_USER_GID
      SSH_PUB_KEY: $SSH_PUB_KEY
      IMAGE_VARIANT: $IMAGE_VARIANT
      CLI_ARGS: $APP_CLI_ARGS
      HF_ACCESS_TOKEN: $HF_ACCESS_TOKEN
    ulimits:
      # Sets the stack size and memory lock limits
      stack: 67108864
      memlock: -1
    # Allows the container to use the host's IPC namespace
    ipc: $CONTAINER_IPC
    ports:
      # Maps the container's SSH and Web service ports to the host's ports
      - "$HOST_SSH_PORT:$CONTAINER_SSH_PORT"
      - "$HOST_WEB_SVC_PORT:$CONTAINER_WEB_SVC_PORT"
      - "$HOST_API_PORT:$CONTAINER_API_PORT"
      - "$HOST_API_STREAM_PORT:$CONTAINER_API_STREAM_PORT"
    volumes:
      # Maps directories from the host to the container
      - "$PWD/.docker/scripts:$APP_INSTALL_ROOT/scripts"
      - ${HF_HOME}:${APP_HF_HOME}
      - $PWD/workspace/characters:$APP_DIR/characters
      - $PWD/workspace/loras:$APP_DIR/loras
      - $PWD/workspace/models:$APP_DIR/models
      - $PWD/workspace/presets:$APP_DIR/presets
      - $PWD/workspace/prompts:$APP_DIR/prompts
      - $PWD/workspace/softprompts:$APP_DIR/softprompts
      - $PWD/workspace/training:$APP_DIR/training
    deploy:
      resources:
        reservations:
          devices:
            # Reserves the specified GPU for the container
            - driver: nvidia
              device_ids: ["${CONTAINER_CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $CONTAINER_NETWORK_NAME
    external: true
