version: "3"

services:
  # Defines a service name
  workspace:
    build:
      # Sets the build context to the current directory
      context: .
      # Specifies the Dockerfile to use for the build
      dockerfile: .docker/Dockerfile.base
      # Specifies build-time variables (ARGs)
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_DEV_BUILD_FROM: $DEV_BUILD_FROM
        ARG_APP_SOURCE_REPO: $APP_SOURCE_REPO
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_DIRNAME: $APP_DIRNAME
        ARG_APP_SOURCE_BRANCH: $APP_SOURCE_BRANCH
    # Sets the image name for the built image
    image: $IMAGE_NAME:$IMAGE_TAG
    # Sets the hostname of the container
    hostname: $CONTAINER_HOSTNAME
    command:
      # Specifies the command to be executed when the container is run
      - $CONTAINER_RUN_COMMAND
    ulimits:
      # Sets the stack size and memory lock limits
      stack: 67108864
      memlock: -1
    ipc: $CONTAINER_IPC
networks:
  default:
    # Sets the name of the default network and makes it external
    name: $CONTAINER_NETWORK_NAME
    external: true
